### PR TITLE
Bump YBM CLI to 0.1.9

### PR DESCRIPTION
**Pull request by cdavid**

### CODE REVIEW

**Review by kc-yb — COMMENTED** [review]
@cdavid Couple of questions:
1. Do we maintain release notes for the revision changes?
2. Is there a way for customers to know that they need to bump up the CLI version to get a particular feature? ie, ybm-cli --check-for-updates
3. The documentation page https://docs.yugabyte.com/preview/yugabyte-cloud/managed-automation/managed-cli/ does not have the latest version information or revision history? Is it planned? Would be good to have.

**Comment by cdavid** [comment]
@kc-yb 
1. Yes, the releases view here contains all the info: https://github.com/yugabyte/ybm-cli/releases (and users can compare revisions)
2. Yes, the CLI will periodically (once per day) check GitHub if there is a new release and prompt the users to update.
3. Yes, but it also feels like we would duplicate all this information from the GitHub repo. While we can automate this, it has not been a priority so far.

**Comment by kc-yb** [comment]
@cdavid This is great. Thanks for the clarifications.

Re (3) - can we add a link in the documentation page to these release versions? Please ignore if the link already exists.

**Comment by kc-yb** [comment]
Re (2) - just wanted to check that we don't do that for json output format. This might break scripting

**Pull request merged**
